// src/services/criticWorkerService.js
// Trusted critic review worker service for CI repair proposals.
//
// Receives a verified repair proposal with a passed validation result,
// constructs a bounded immutable review bundle from proposal state,
// runs a deterministic critic assessment, and records the structured review
// through the canonical recordCriticReview() path with actor_kind: critic_worker.
//
// Strict boundaries:
// - Input: proposal state only (no open-ended repo access)
// - Output: only the critic_review field (via recordCriticReview)
// - No GitHub API calls, no repository writes, no branch/PR creation
// - Critic cannot certify its own inputs
// - Approve is unconditionally rejected until a receipt backend exists
// - Until a real executor exists, only reject is possible

import { logger } from "../lib/logger.js";
import {
  getProposal,
  recordCriticReview,
  contentHash,
  buildCriticInputBundle,
  computeReviewFingerprint,
} from "./repairProposalService.js";
import { ACTOR_KINDS } from "./repairAuthorityService.js";

const ACTOR = ACTOR_KINDS.CRITIC_WORKER;

// ════════════════════════════════════════════════════════════════════════════
// RE-EXPORTS — shared canonical functions from repairProposalService
// ════════════════════════════════════════════════════════════════════════════

export { buildCriticInputBundle, computeReviewFingerprint };

// ════════════════════════════════════════════════════════════════════════════
// CRITIC ASSESSMENT — deterministic stub
// ════════════════════════════════════════════════════════════════════════════

/**
 * Run deterministic critic assessment on a bounded input bundle.
 *
 * This is a deterministic stub engine. In production, this would be
 * replaced by an LLM-backed critic that receives the same bounded bundle.
 *
 * The stub always returns reject with a blocking finding because no
 * execution receipt exists to prove the patch actually passed validation.
 * This is the correct behavior until a real executor lands.
 *
 * @param {object} inputBundle - the bounded critic input
 * @returns {object} structured critic assessment
 */
export function assessCriticInput(inputBundle) {
  const findings = [];
  const blockingFindings = [];

  // No execution receipt on validation_result — cannot independently verify
  findings.push({
    code: "VALIDATION_RECEIPT_BOUND",
    severity: "blocking",
    detail: "No execution receipt on validation_result — cannot verify actual execution",
    evidence_ref: inputBundle.verification_fingerprint,
  });
  blockingFindings.push("VALIDATION_RECEIPT_BOUND");

  return {
    verdict: "reject",
    findings,
    blocking_findings: blockingFindings,
    risk_summary: "Blocked: validation outcome not independently verified",
    limitations: "Generated by deterministic stub engine — requires human review.",
  };
}

// ════════════════════════════════════════════════════════════════════════════
// TRUSTED CRITIC REVIEW PIPELINE
// ════════════════════════════════════════════════════════════════════════════

/**
 * Assess and record a critic review for a verified proposal.
 *
 * @param {number} proposalId - repair proposal ID
 * @param {object} [options]
 * @param {string} [options.correlation_id] - correlation ID for audit trail
 * @param {string} [options.source_delivery_id] - source provenance
 * @returns {Promise<object>} updated proposal with critic_review
 */
export async function reviewProposal(proposalId, options = {}) {
  const { correlation_id, source_delivery_id } = options;

  if (!proposalId) throw new Error("proposalId is required");

  // ── 1. Fetch proposal ────────────────────────────────────────────────────
  const proposal = await getProposal(proposalId);
  if (!proposal) {
    throw new Error(`Repair proposal not found: ${proposalId}`);
  }

  // ── 2. Status gate: only verified ────────────────────────────────────────
  if (proposal.status !== "verified") {
    throw new Error(
      `Critic review requires status 'verified' (current: '${proposal.status}')`
    );
  }

  // ── 3. Build bounded critic input from proposal state ─────────────────────
  // Uses the SAME canonical builder as recordCriticReview() so that the
  // critic_input_hash is reproducible from locked state.
  const criticInput = buildCriticInputBundle(proposal);
  const criticInputHash = contentHash(criticInput);

  // ── 4. Run deterministic critic assessment ───────────────────────────────
  const assessment = assessCriticInput(criticInput);

  // ── 5. Compute review fingerprint from canonical values ──────────────────
  // Uses the SAME formula as recordCriticReview() so that the recorder
  // can verify the submitted fingerprint against the recomputed value.
  const policyVersion = null;
  const review_fingerprint = computeReviewFingerprint(
    criticInputHash,
    assessment.verdict,
    assessment.findings,
    assessment.blocking_findings,
    policyVersion
  );

  // ── 6. Build review input for canonical recording ────────────────────────
  const reviewInput = {
    verdict: assessment.verdict,
    review_fingerprint,
    critic_input_hash: criticInputHash,
    patch_artifact_hash: criticInput.patch_artifact_hash,
    verification_fingerprint: criticInput.verification_fingerprint,
    findings: assessment.findings,
    blocking_findings: assessment.blocking_findings,
    risk_summary: assessment.risk_summary,
    limitations: assessment.limitations,
    policy_version: policyVersion,
  };

  // ── 7. Record through canonical path ─────────────────────────────────────
  const result = await recordCriticReview(
    proposalId,
    reviewInput,
    {
      actor: ACTOR,
      actor_kind: ACTOR,
      expected_version: proposal.version,
      correlation_id,
      source_delivery_id,
    }
  );

  logger.info(
    { proposal_id: proposalId, correlation_id, verdict: assessment.verdict },
    "Critic review recorded for repair proposal"
  );

  return result;
}
